switching from unavaiable to none to correct error
... like:

ValueError: Sensor sensor.tacoma_box_humidity_rounded has device
class 'humidity', state class 'None' unit '%' and suggested
precision 'None' thus indicating it has a numeric value; however,
 it has the non-numeric value: 'unavailable' (<class 'str'>)